### ISSUE TITLE
notification for deadlines, signups and any other promotional material

### ISSUE THREAD

**Issue by anudeep-17** [ualbany-software-engineering/mustang-StudyEasy#33]

**Comment by anudeep-17** [comment]
@Srujan560 @AbidKhawaja, perfect job, profound appreciation 💯 👍 leave a comment about the feature and close the issue.
Cheers!

**Comment by Srujan560** [comment]
Yeah... I will see what I can do

**Comment by anudeep-17** [comment]
👍🏻
