### ISSUE TITLE
monochorme

### ISSUE THREAD

**Issue by anudeep-17** [ualbany-software-engineering/mustang-StudyEasy#40]

**Comment by anudeep-17** [comment]
currently disturbed due a errored push to main, resetting the head but dev wise we are done 👍🏻 
@DheerajNani7 @ForumShah8 leave your comments and close the issue 
good job both 💯

**Comment by DheerajNani7** [comment]
Good job! @anudeep-17 @ForumShah8

**Comment by ForumShah8** [comment]
It's all done, I'm closing this issue now!
