### ISSUE TITLE
trending colleges

### ISSUE THREAD

**Issue by anudeep-17** [ualbany-software-engineering/mustang-StudyEasy#41]

**Comment by anudeep-17** [comment]
Implemented trending colleges, and developed a schema of firebase firestore to collect the data of clicks on universities and update them on the university page.
it was fun working on this..... the best issue I ever worked 💘 
@DheerajNani7 good job.
 close the issue with a comment !

**Comment by DheerajNani7** [comment]
Hell ya it took a lot of time figuring it out and finishing this part. great job @anudeep-17 !!🤝
